
become: true 
tasks:
 - name: "Install dependencies"
    apt: 
     pkg:
      - apt-transport-https 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  - name: "Get Docker Apt Key"  
    ansible.built.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present 
  - name: "Add Docker repo"
    ansible.built.apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
      state: present 

  - name: "Install docker"
    apt: 
     pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io 

  - name: "add user to docker groups"
    ansible.builtin.user: 
      name: amorr 
      groups: docker
      append: yes 
      
