- hosts: 
  - managers 
  - workers 
  become: true 
  roles: 
  - install-docker 

- hosts: managers 
  become: true 
  roles:
  - swarm-master 

- hosts: workers 
  become: true 
  roles:
  - swarm-worker

- hosts: load-balance
  become: true
  roles:
  - nginx
  

