- hosts: all 
  become: true 
  roles: 
  - install-docker 

- hosts: managers 
  become: true 
  roles:
  - swarm-master 

- hosts: workers 
  become: true 
  roles:
  - swarm-worker2
  - swarm-worker3

