version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
   lottery_numbers_server:
    container_name: lottery_numbers_server
    image: absgeorge/lottery_numbers_server
    build: ./serviceone
    deploy:
      replicas: 4  
  lottery_number_api:
    container_name: lottery_number_api
    image: absgeorge/lottery_number_api
    build: ./servicetwo
    deploy:
      replicas: 3
  lottery_alpha_api:
    container_name: lottery_alpha_api
    image: absgeorge/lottery_alpha_api
    build: ./servicethree
    deploy:
      replicas: 4
  results_api:
    container_name: results_api
    image: absgeorge/results_api
    build: ./servicefour
    environment:
     DATABASE_URI: ${DATABASE_URI}
