version: "3.8"
services:
  loterry_numbers_server:
    container_name: lottery_numbers_server
    image: absgeorge/lottery_numbers_server
    build: ./serviceone
    ports: 
    - published: 5000
      target: 5000
  lottery_number_api:
    container_name: lottery_number_api
    image: absgeorge/lottery_number_api
    build: ./servicetwo
  lottery_alpha_api:
    container_name: lottery_alpha_api
    image: absgeorge/lottery_alpha_api
    build: ./servicethree
  results_api:
    container_name: results_api
    image: absgeorge/results_api
    build: ./servicefour
    environment:
     DATABASE_URI: ${DATABASE_URI}