---
- name: Add worker
  docker_swarm:
    state: join
    advertise_addr: swarm-worker2
    join_token: "{{ hostvars['swarm-master']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarm-managermaster:2377' ]