---
- name: "Install dependencies"
  apt: 
    pkg:
    - apt-transport-https 
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip
- name: "Get Docker Apt Key"  
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 
- name: "Add Docker repo"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present 

- name: "Install docker"
  apt: 
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io 

- name: "add user to docker groups"
  ansible.builtin.user: 
    name: amorr 
    groups: docker
    append: yes 

- name: "Install Docker with Pip"
  pip:
    name: docker 
  